apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "vault.fullname" . }}
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
